"""Initial schema

Revision ID: cdeaa039dcd4
Revises: 
Create Date: 2026-04-11 01:13:57.924733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdeaa039dcd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('dataset_path', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('bias_metrics', sa.JSON(), nullable=True),
    sa.Column('mitigation_history', sa.JSON(), nullable=True),
    sa.Column('oversight_decision', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
