"""EU AI Act regulation mapping and risk classification.

Maps FairCheck analysis results to EU AI Act articles (9, 10, 13, 14, 17),
produces article-by-article compliance evidence, and generates
risk classification from the metric ensemble.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from faircheck.reports.data import ReportData


@dataclass
class ArticleMapping:
    """Single EU AI Act article mapping with evidence."""

    article: str
    title: str
    requirement: str
    report_section: str
    status: str  # "addressed" | "partially_addressed" | "not_addressed"
    evidence: str


@dataclass
class RegulationReport:
    """Complete regulation mapping report."""

    regulation: str  # "eu_ai_act"
    risk_classification: str  # "high" | "medium" | "low"
    article_mappings: list[ArticleMapping] = field(default_factory=list)
    disclaimer: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "regulation": self.regulation,
            "risk_classification": self.risk_classification,
            "article_mappings": [
                {
                    "article": m.article,
                    "title": m.title,
                    "requirement": m.requirement,
                    "report_section": m.report_section,
                    "status": m.status,
                    "evidence": m.evidence,
                }
                for m in self.article_mappings
            ],
            "disclaimer": self.disclaimer,
        }


class RegulationMapper:
    """Maps FairCheck analysis results to EU AI Act articles."""

    DISCLAIMER = (
        "DISCLAIMER: This report is generated by automated software and is "
        "provided as guidance only. It does not constitute legal certification "
        "of compliance with the EU Artificial Intelligence Act (Regulation (EU) "
        "2024/1689) or any other regulation. Organizations deploying AI systems "
        "should seek qualified legal counsel to verify regulatory compliance. "
        "The risk classification and article mappings herein are based on "
        "automated bias metrics and may not capture all dimensions of "
        "regulatory requirements."
    )

    def map(self, report_data: ReportData) -> RegulationReport:
        """Map analysis results to EU AI Act articles.

        Parameters
        ----------
        report_data : ReportData
            The report data container.

        Returns
        -------
        RegulationReport
            Complete regulation mapping with risk classification.
        """
        risk = self._classify_risk(report_data.analysis_results)
        mappings = self._build_mappings(report_data)
        return RegulationReport(
            regulation="eu_ai_act",
            risk_classification=risk,
            article_mappings=mappings,
            disclaimer=self.DISCLAIMER,
        )

    def _classify_risk(self, analysis: dict[str, Any]) -> str:
        """Derive risk classification from metric ensemble.

        - high: any metric fails
        - medium: any metric warns, none fail
        - low: all metrics pass
        """
        results = analysis.get("results", {})
        has_fail = False
        has_warn = False
        for attr_data in results.values():
            for m_data in attr_data.get("metrics", {}).values():
                status = m_data.get("status", "")
                if status == "fail":
                    has_fail = True
                elif status == "warning":
                    has_warn = True
        if has_fail:
            return "high"
        if has_warn:
            return "medium"
        return "low"

    def _build_mappings(self, data: ReportData) -> list[ArticleMapping]:
        """Build article-by-article mappings."""
        has_analysis = bool(data.analysis_results.get("results"))
        has_model_card = bool(data.training_data_description)
        has_oversight = data.oversight is not None
        has_mitigation = data.mitigation is not None

        mappings = [
            # REG-01: Article 9 — Risk Management
            ArticleMapping(
                article="Article 9",
                title="Risk Management System",
                requirement=(
                    "High-risk AI systems shall have a risk management system "
                    "established, implemented, documented, and maintained."
                ),
                report_section="Bias Analysis Results, Mitigation Applied",
                status="addressed" if has_analysis else "not_addressed",
                evidence=(
                    "Automated bias analysis identifies fairness risks across "
                    "protected attributes. Metric thresholds provide quantitative "
                    "risk boundaries."
                    + (
                        " Mitigation measures have been applied."
                        if has_mitigation
                        else " No mitigation applied yet."
                    )
                ),
            ),
            # REG-02: Article 10 — Data Governance
            ArticleMapping(
                article="Article 10",
                title="Data and Data Governance",
                requirement=(
                    "Training, validation and testing data sets shall be subject "
                    "to appropriate data governance and management practices."
                ),
                report_section="Model Card, Demographic Performance Breakdown",
                status=(
                    "addressed" if has_model_card else "partially_addressed"
                ),
                evidence=(
                    f"Training data description: {data.training_data_description or 'Not provided'}. "
                    "Per-group performance breakdown enables bias monitoring "
                    "across demographic subgroups."
                ),
            ),
            # REG-03: Article 13 — Transparency
            ArticleMapping(
                article="Article 13",
                title="Transparency and Provision of Information",
                requirement=(
                    "High-risk AI systems shall be designed and developed in "
                    "such a way as to ensure that their operation is sufficiently "
                    "transparent."
                ),
                report_section="Model Card, Executive Summary, Appendix",
                status="addressed" if has_model_card else "partially_addressed",
                evidence=(
                    f"Intended use: {data.intended_use or 'Not specified'}. "
                    f"Known limitations: {data.known_limitations or 'Not documented'}. "
                    "Methodology appendix details all metrics and their computation."
                ),
            ),
            # REG-04: Article 14 — Human Oversight
            ArticleMapping(
                article="Article 14",
                title="Human Oversight",
                requirement=(
                    "High-risk AI systems shall be designed and developed in "
                    "such a way as to allow effective oversight by natural persons."
                ),
                report_section="Human Oversight Record",
                status="addressed" if has_oversight else "not_addressed",
                evidence=(
                    (
                        f"Oversight recorded by {data.oversight.get('reviewer', 'Unknown')}. "
                        f"Decision: {data.oversight.get('decision', 'N/A')}."
                    )
                    if has_oversight
                    else (
                        "No human oversight decision recorded. A compliance "
                        "officer should review and sign off on this report."
                    )
                ),
            ),
            # REG-05: Article 17 — Quality Management
            ArticleMapping(
                article="Article 17",
                title="Quality Management System",
                requirement=(
                    "Providers of high-risk AI systems shall put a quality "
                    "management system in place."
                ),
                report_section="Appendix, Session Metadata",
                status="addressed" if data.session_id else "partially_addressed",
                evidence=(
                    f"Audit session tracked with ID: {data.session_id or 'N/A'}. "
                    "Full audit trail preserved in local session store. "
                    "Regular re-assessment recommended."
                ),
            ),
        ]

        return mappings
